name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run code
      run: python app.py

    - name: Run fake lint
      run: echo "Running lint (this is a placeholder)"

    - name: Run fake build
      run: echo "Building project (this is a placeholder)"

    - name: Notify
      run: echo "Notification: Workflow completed!"
